name: study_mate
description: A digital student personal assistant.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.0.2

  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  ionicons: ^0.1.2

  intl: ^0.17.0
  file_picker: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  flutter_pdfview: ^1.2.0
  awesome_notifications: ^0.0.6+10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gilmer
      fonts:
        - asset: assets/fonts/Gilmer-Light.otf
          weight: 300
        - asset: assets/fonts/Gilmer-Regular.otf
        - asset: assets/fonts/Gilmer-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilmer-Bold.otf
          weight: 700
        - asset: assets/fonts/Gilmer-Heavy.otf
          weight: 900
